// --------------------- DATA ---------------------
const recipes = [
  {
    id: 1,
    day: 1,
    title: "Palak Paneer",
    category: "dinner",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    ingredients: [
      "250g paneer",
      "500g spinach",
      "2 onions",
      "3 tomatoes",
      "Spices",
    ],
    instructions: ["Blanch spinach", "Make gravy", "Add paneer", "Simmer"],
  },
  {
    id: 2,
    day: 1,
    title: "Dal Tadka",
    category: "lunch",
    image:
      "https://www.scrumptiously.com/wp-content/uploads/2024/10/MoongDalTadka.webp?w=400",
    ingredients: ["200g toor dal", "Onions", "Tomatoes", "Ghee", "Cumin seeds"],
    instructions: ["Cook dal", "Prepare tadka", "Mix together"],
  },
  {
    id: 3,
    day: 1,
    title: "Gulab Jamun",
    category: "dessert",
    image:
      "https://www.cadburydessertscorner.com/hubfs/dc-website-2022/articles/soft-gulab-jamun-recipe-for-raksha-bandhan-from-dough-to-syrup-all-you-need-to-know/soft-gulab-jamun-recipe-for-raksha-bandhan-from-dough-to-syrup-all-you-need-to-know.webp?w=400",
    ingredients: ["Khoya", "Maida", "Sugar syrup", "Cardamom"],
    instructions: ["Make dough", "Fry balls", "Soak in syrup"],
  },
  {
    id: 4,
    day: 2,
    title: "Chole Bhature",
    category: "lunch",
    image:
      "https://saptrishifoods.com/cdn/shop/articles/cholebhature.png?v=1745488999?w=400",
    ingredients: ["Chickpeas", "Maida", "Yogurt", "Spices"],
    instructions: ["Cook chole", "Make bhatura dough", "Fry bhature"],
  },
  {
    id: 5,
    day: 2,
    title: "Butter Chicken",
    category: "dinner",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    ingredients: ["Chicken", "Butter", "Cream", "Tomato puree", "Kasuri methi"],
    instructions: [
      "Marinate chicken",
      "Make gravy",
      "Add chicken",
      "Finish with cream",
    ],
  },
  {
    id: 6,
    day: 2,
    title: "Rasmalai",
    category: "dessert",
    image:
      "https://palatesdesire.com/wp-content/uploads/2022/09/Rasmalai-recipe@palates-desire.jpg?w=400",
    ingredients: ["Milk", "Paneer", "Sugar", "Saffron", "Cardamom"],
    instructions: ["Make chenna balls", "Cook in milk", "Chill"],
  },
  {
    id: 7,
    day: 3,
    title: "Biryani",
    category: "dinner",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
    ingredients: [
      "Basmati rice",
      "Chicken/Mutton",
      "Yogurt",
      "Saffron",
      "Spices",
    ],
    instructions: ["Marinate meat", "Cook rice", "Layer", "Dum cook"],
  },
  {
    id: 8,
    day: 3,
    title: "Aloo Paratha",
    category: "lunch",
    image:
      "https://www.kingarthurbaking.com/sites/default/files/2025-07/Aloo-Paratha-_2025_Lifestyle_H_2435.jpg?w=400",
    ingredients: ["Wheat flour", "Potatoes", "Spices", "Butter"],
    instructions: [
      "Make dough",
      "Prepare filling",
      "Stuff and roll",
      "Cook on tawa",
    ],
  },
  {
    id: 9,
    day: 3,
    title: "Kheer",
    category: "dessert",
    image:
      "https://c.ndtvimg.com/2018-10/6n7i40g8_sharad-purnima-2018-kheer-recipe-and-benefits_625x300_23_October_18.jpg?w=400",
    ingredients: ["Rice", "Milk", "Sugar", "Cardamom", "Dry fruits"],
    instructions: ["Boil rice in milk", "Add sugar", "Garnish"],
  },
  {
    id: 10,
    day: 4,
    title: "Rajma Chawal",
    category: "lunch",
    image:
      "https://www.secondrecipe.com/wp-content/uploads/2017/08/rajma-chawal-1.jpg?w=400",
    ingredients: ["Kidney beans", "Rice", "Onions", "Tomatoes", "Spices"],
    instructions: ["Soak rajma", "Cook with spices", "Serve with rice"],
  },
  {
    id: 11,
    day: 4,
    title: "Paneer Tikka",
    category: "dinner",
    image: "https://orders.popskitchen.in/storage/2024/09/image-358.png?w=400",
    ingredients: ["Paneer", "Bell peppers", "Yogurt", "Spices"],
    instructions: ["Marinate paneer", "Skewer", "Grill or bake"],
  },
  {
    id: 12,
    day: 4,
    title: "Jalebi",
    category: "dessert",
    image:
      "https://www.chilitochoc.com/wp-content/uploads/2025/03/instant-jalebi-recipe-500x375.jpg?w=400",
    ingredients: ["Maida", "Yogurt", "Sugar syrup", "Food color"],
    instructions: ["Ferment batter", "Pipe in oil", "Soak in syrup"],
  },
  {
    id: 13,
    day: 5,
    title: "Masala Dosa",
    category: "Breakfast",
    image:
      "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__1200_0_0_0_auto.jpg?w=400",
    ingredients: ["Rice", "Urad dal", "Potato", "Spices", "Coconut chutney"],
    instructions: [
      "Ferment batter",
      "Make potato filling",
      "Cook dosa",
      "Serve with chutney",
    ],
  },
  {
    id: 14,
    day: 5,
    title: "Kadai Paneer",
    category: "dinner",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    ingredients: ["Paneer", "Capsicum", "Tomatoes", "Kadai masala"],
    instructions: ["Roast spices", "Cook gravy", "Add paneer", "Garnish"],
  },
  {
    id: 15,
    day: 5,
    title: "Gajar Halwa",
    category: "dessert",
    image:
      "https://www.milkmaid.in/sites/default/files/2022-12/Gajar-Halwa-335x300.jpg?w=400",
    ingredients: ["Carrots", "Milk", "Ghee", "Sugar", "Cardamom"],
    instructions: ["Grate carrots", "Cook in milk", "Add ghee and sugar"],
  },
  {
    id: 16,
    day: 6,
    title: "Pav Bhaji",
    category: "lunch",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7TjDnTHHA3FocHcSF_EAhdK2b7VxjfdNp3g&s?w=400",
    ingredients: ["Mixed vegetables", "Pav buns", "Butter", "Pav bhaji masala"],
    instructions: [
      "Mash vegetables",
      "Add masala",
      "Cook with butter",
      "Serve with pav",
    ],
  },
  {
    id: 17,
    day: 6,
    title: "Rogan Josh",
    category: "dinner",
    image:
      "https://assets.farmison.com/images/recipe-detail-1380/78170-lamb-rogan-josh.jpg?w=400",
    ingredients: ["Mutton", "Yogurt", "Kashmiri chili", "Spices"],
    instructions: ["Marinate meat", "Slow cook", "Add spices"],
  },
  {
    id: 18,
    day: 6,
    title: "Kulfi",
    category: "dessert",
    image:
      "https://vaya.in/recipes/wp-content/uploads/2018/12/Kesar-Kulfi..jpg?w=400",
    ingredients: ["Condensed milk", "Cream", "Cardamom", "Pistachios"],
    instructions: ["Mix ingredients", "Freeze in molds", "Serve"],
  },
  {
    id: 19,
    day: 7,
    title: "Idli Sambhar",
    category: "Breakfast",
    image:
      "https://vaya.in/recipes/wp-content/uploads/2018/02/Idli-and-Sambar-1.jpg?w=400",
    ingredients: [
      "Rice",
      "Urad dal",
      "Vegetables",
      "Tamarind",
      "Sambhar powder",
    ],
    instructions: ["Ferment batter", "Steam idlis", "Cook sambhar"],
  },
  {
    id: 20,
    day: 7,
    title: "Fish Curry",
    category: "dinner",
    image:
      "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/10/fish-curry-recipe.jpg?w=400",
    ingredients: ["Fish", "Coconut", "Tamarind", "Curry leaves", "Spices"],
    instructions: ["Marinate fish", "Make coconut gravy", "Add fish", "Simmer"],
  },
  {
    id: 21,
    day: 7,
    title: "Mysore Pak",
    category: "dessert",
    image:
      "https://i.ytimg.com/vi/jkoGehGWw08/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBTdyzWetagQmnMS9nwPN5oTfz2dw?w=400",
    ingredients: ["Besan", "Ghee", "Sugar", "Cardamom"],
    instructions: ["Make sugar syrup", "Roast besan", "Mix and set"],
  },
  {
    id: 22,
    day: 8,
    title: "Vada Pav",
    category: "lunch",
    image:
      "https://blog.swiggy.com/wp-content/uploads/2024/11/Image-1_mumbai-vada-pav-1024x538.png?w=400",
    ingredients: ["Potatoes", "Pav", "Besan", "Spices", "Green chutney"],
    instructions: ["Make potato vada", "Fry", "Serve in pav"],
  },
  {
    id: 23,
    day: 8,
    title: "Malai Kofta",
    category: "dinner",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsT8TUD-NzEQeESGXCTvbEFMbcMp-heDW-Kw&s?w=400",
    ingredients: ["Paneer", "Potato", "Cashews", "Cream", "Tomato gravy"],
    instructions: ["Make kofta balls", "Fry", "Prepare gravy", "Add kofta"],
  },
  {
    id: 24,
    day: 8,
    title: "Shrikhand",
    category: "dessert",
    image:
      "https://madhurasrecipe.com/wp-content/uploads/2023/03/Shrikhand-Featured.jpg?w=400",
    ingredients: ["Yogurt", "Sugar", "Saffron", "Cardamom", "Dry fruits"],
    instructions: ["Hang yogurt", "Mix with sugar", "Add flavors"],
  },
  {
    id: 25,
    day: 9,
    title: "Poha",
    category: "Breakfast",
    image:
      "https://www.mrishtanna.com/wp-content/uploads/2018/04/poha-indian-breakfast-recipe.jpg?w=400",
    ingredients: ["Flattened rice", "Onions", "Peanuts", "Turmeric", "Lemon"],
    instructions: ["Rinse poha", "Temper spices", "Mix", "Garnish"],
  },
  {
    id: 26,
    day: 9,
    title: "Chicken Korma",
    category: "dinner",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    ingredients: ["Chicken", "Yogurt", "Cashew paste", "Spices"],
    instructions: ["Marinate chicken", "Make korma gravy", "Slow cook"],
  },
  {
    id: 27,
    day: 9,
    title: "Besan Ladoo",
    category: "dessert",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGK0tVTEd3xWi1A-t-WIy4rronK_sCarBd-g&s?w=400",
    ingredients: ["Besan", "Ghee", "Sugar", "Cardamom", "Almonds"],
    instructions: ["Roast besan", "Mix with sugar", "Shape ladoos"],
  },
  {
    id: 28,
    day: 10,
    title: "Upma",
    category: "Breakfast",
    image:
      "https://myfoodstory.com/wp-content/uploads/2022/11/Vegetable-Upma-3.jpg?w=400",
    ingredients: ["Rava/Sooji", "Vegetables", "Curry leaves", "Mustard seeds"],
    instructions: ["Roast rava", "Temper spices", "Add water", "Cook"],
  },
  {
    id: 29,
    day: 10,
    title: "Dum Aloo",
    category: "dinner",
    image:
      "https://www.ohmyveg.co.uk/wp-content/uploads/2024/03/Dum-Aloo-1-e1722869537163.jpg?w=400",
    ingredients: [
      "Baby potatoes",
      "Yogurt",
      "Tomatoes",
      "Kashmiri chili",
      "Spices",
    ],
    instructions: ["Fry potatoes", "Make gravy", "Dum cook"],
  },
  {
    id: 30,
    day: 10,
    title: "Peda",
    category: "dessert",
    image: "https://i.ytimg.com/vi/3sr4D9H2rrE/maxresdefault.jpg?w=400",
    ingredients: ["Khoya", "Sugar", "Cardamom", "Saffron"],
    instructions: ["Cook khoya and sugar", "Shape pedas", "Garnish"],
  },
  {
    id: 31,
    day: 11,
    title: "Kachori",
    category: "lunch",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/8f/Rajasthani_Raj_Kachori.jpg?w=400",
    ingredients: ["Maida", "Moong dal", "Spices", "Oil"],
    instructions: ["Make dough", "Prepare filling", "Stuff and fry"],
  },
  {
    id: 32,
    day: 11,
    title: "Prawn Curry",
    category: "dinner",
    image:
      "https://img.taste.com.au/7xu3Pa5L/w1200-h1200-cfill-q80/taste/2010/01/easy-curried-prawns-177563-2.jpg?w=400",
    ingredients: ["Prawns", "Coconut", "Tomatoes", "Curry leaves", "Spices"],
    instructions: ["Clean prawns", "Make coconut gravy", "Add prawns", "Cook"],
  },
  {
    id: 33,
    day: 11,
    title: "Rasgulla",
    category: "dessert",
    image:
      "https://madhurasrecipe.com/wp-content/uploads/2023/10/Rasgulla-Featured-Image.jpg?w=400",
    ingredients: ["Paneer/Chenna", "Sugar", "Water", "Cardamom"],
    instructions: ["Make chenna balls", "Boil in sugar syrup", "Cool"],
  },
  {
    id: 34,
    day: 12,
    title: "Medu Vada",
    category: "Breakfast",
    image:
      "https://www.chefkunalkapur.com/wp-content/uploads/2021/06/Medu-Vada-1300x867.jpg?v=1623509746?w=400",
    ingredients: ["Urad dal", "Green chili", "Curry leaves", "Ginger"],
    instructions: ["Grind dal", "Shape vadas", "Deep fry"],
  },
  {
    id: 35,
    day: 12,
    title: "Tandoori Chicken",
    category: "dinner",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    ingredients: ["Chicken", "Yogurt", "Tandoori masala", "Lemon"],
    instructions: ["Marinate overnight", "Grill or bake", "Serve hot"],
  },
  {
    id: 36,
    day: 12,
    title: "Phirni",
    category: "dessert",
    image:
      "https://weikfield.com/wp-content/uploads/2024/08/Phirni-Custard.jpg?w=400",
    ingredients: ["Rice", "Milk", "Sugar", "Saffron", "Rose water"],
    instructions: [
      "Grind soaked rice",
      "Cook in milk",
      "Chill in earthen pots",
    ],
  },
  {
    id: 37,
    day: 13,
    title: "Misal Pav",
    category: "lunch",
    image:
      "https://c.ndtvimg.com/2025-05/qdcp3aj4_food_625x300_30_May_25.jpg?im=FitAndFill,algorithm=dnn,width=620,height=350?im=FaceCrop,algorithm=dnn,width=1200,height=886?w=400",
    ingredients: ["Sprouts", "Onions", "Farsan", "Pav", "Spicy gravy"],
    instructions: ["Cook sprouts", "Make rassa", "Assemble", "Serve with pav"],
  },
  {
    id: 38,
    day: 13,
    title: "Mutton Biryani",
    category: "dinner",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400",
    ingredients: ["Mutton", "Basmati rice", "Yogurt", "Saffron", "Spices"],
    instructions: ["Marinate mutton", "Par-cook rice", "Layer", "Dum cook"],
  },
  {
    id: 40,
    day: 14,
    title: "Aloo Tikki",
    category: "lunch",
    image: "https://static.toiimg.com/photo/53250592.cms?w=400",
    ingredients: ["Potatoes", "Peas", "Spices", "Breadcrumbs"],
    instructions: [
      "Mash potatoes",
      "Add filling",
      "Shape tikkis",
      "Shallow fry",
    ],
  },
];
